export const SAGA_QUERY_BY_CITY = "SAGA_QUERY_BY_CITY";
export const UPDATE_RESTAURANT_LIST = "UPDATE_RESTAURANT_LIST";
export const UPDATE_CURRENT_SEARCH_RESULT = "UPDATE_CURRENT_SEARCH_RESULT";
export const UPDATE_CURRENT_SEARCH_FILTER = "UPDATE_CURRENT_SEARCH_FILTER";